spring:
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:file:.env[.properties]
  
  # 프로필 설정
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # 개발 도구 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:repit}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 10
      minimum-idle: 5

  # 카카오 소셜 로그인
  kakao:
    client_id: ${REST_API_KEY}
    redirect_uri: http://localhost:8080/api/auth/login/kakao
    
  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
    
  # 서버 설정
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
  # Thymeleaf 설정 (카카오 로그인 페이지용)
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# 파일 감지 설정
file:
  watch:
    directory: ${FILE_WATCH_DIRECTORY:/Users/pado/repit/repit-jetson/output}
    pattern: ${FILE_WATCH_PATTERN:.*_report_\\d+\\.txt$}
    enabled: ${FILE_WATCH_ENABLED:true}

# 로깅 설정
logging:
  level:
    com.repit.api: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.repit.api.controller

# 서버 포트 설정
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api