socket:
    port: 8080
socket-server:
    port: 8081
    host: 54.180.156.150

socket-client:
    host: localhost
    port: 8088

spring:
    datasource:
        driver-class-name:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect